experimentName: HELIX hyper-param searching
authorName: MiBah Cat
trialConcurrency: 1
trainingServicePlatform: local
searchSpacePath: HELIX_physionet_2012_tuning_space.json
multiThread: true
useAnnotation: false
maxExperimentDuration: 72h
maxTrialNumber: 100
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: minimize

trial:
    command: enable_tuning=1 pypots-cli tuning --model pypots.imputation.HELIX --train_set ../../data/generated_datasets/physionet_2012_rate01_point/train.h5 --val_set ../../data/generated_datasets/physionet_2012_rate01_point/val.h5
    codeDir: .
    gpuNum: 1

localConfig:
    useActiveGpu: true
    maxTrialNumPerGpu: 1
    gpuIndices: [0]